# Generated by Django 3.1.3 on 2020-11-10 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('category_name',),
            },
        ),
        migrations.CreateModel(
            name='ProductIphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование продукта')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение продукта')),
                ('description', models.TextField(null=True, verbose_name='Описание продукта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена продукта')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Количество товара на складе')),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('diagonal', models.CharField(max_length=255, verbose_name='Диагональ')),
                ('display_type', models.CharField(max_length=255, verbose_name='Тип дисплея')),
                ('memory', models.CharField(max_length=255, verbose_name='Память')),
                ('resolution', models.CharField(max_length=255, verbose_name='Разрешение экрана')),
                ('accum_volume', models.CharField(max_length=255, verbose_name='Объем батареи')),
                ('main_cam_mp', models.CharField(max_length=255, verbose_name='Основная камера')),
                ('frontal_cam_mp', models.CharField(max_length=255, verbose_name='Фронтальная камера')),
                ('face_id', models.BooleanField(default=True, verbose_name='Наличие FaceID')),
                ('face_id_technology', models.CharField(blank=True, max_length=255, null=True, verbose_name='Технология FaceID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categoryproduct', verbose_name='Категория')),
            ],
            options={
                'ordering': ('title',),
                'abstract': False,
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ProductIpad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование продукта')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение продукта')),
                ('description', models.TextField(null=True, verbose_name='Описание продукта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена продукта')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Количество товара на складе')),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('diagonal', models.CharField(max_length=255, verbose_name='Диагональ')),
                ('display_type', models.CharField(max_length=255, verbose_name='Тип дисплея')),
                ('memory', models.CharField(max_length=255, verbose_name='Память')),
                ('resolution', models.CharField(max_length=255, verbose_name='Разрешение экрана')),
                ('accum_volume', models.CharField(max_length=255, verbose_name='Объем батареи')),
                ('main_cam_mp', models.CharField(max_length=255, verbose_name='Основная камера')),
                ('frontal_cam_mp', models.CharField(max_length=255, verbose_name='Фронтальная камера')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categoryproduct', verbose_name='Категория')),
            ],
            options={
                'ordering': ('title',),
                'abstract': False,
                'index_together': {('id', 'slug')},
            },
        ),
    ]
