# Generated by Django 3.1.3 on 2020-11-10 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductIpad',
            new_name='Ipad',
        ),
        migrations.RenameModel(
            old_name='ProductIphone',
            new_name='Iphone',
        ),
    ]
