# Generated by Django 3.1.3 on 2020-11-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201121_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproduct',
            name='imageT',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение продуктаT'),
        ),
    ]
