# Generated by Django 3.1.3 on 2020-11-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_categoryproduct_imaget'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageT', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='categoryproduct',
            name='imageT',
        ),
    ]
