# Generated by Django 3.1.3 on 2020-11-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201124_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimage',
            name='imageT',
            field=models.ImageField(upload_to='', verbose_name='Сюда фоточку'),
        ),
    ]
