# Generated by Django 3.1.3 on 2020-11-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20201122_1511'),
        ('main', '0006_auto_20201126_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(related_name='related_order', to='orders.Order', verbose_name='Заказы покупателя'),
        ),
    ]
