# Generated by Django 3.1.6 on 2021-02-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210226_1222'),
        ('specification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='features_for_product', to='specification.ProductFeatures'),
        ),
        migrations.DeleteModel(
            name='CategoryFeature',
        ),
        migrations.DeleteModel(
            name='FeatureValidator',
        ),
        migrations.DeleteModel(
            name='ProductFeatures',
        ),
    ]
