# Generated by Django 3.1.6 on 2021-03-04 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0001_initial'),
        ('orders', '0008_remove_order_customer'),
        ('main', '0010_auto_20210226_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_product', to='main.categoryproduct', verbose_name='Категория'),
        ),
        migrations.DeleteModel(
            name='Ipad',
        ),
    ]
