# Generated by Django 3.1.6 on 2021-03-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0001_initial'),
        ('main', '0012_auto_20210304_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='features_for_product', to='specification.ProductFeatures'),
        ),
    ]
