# Generated by Django 3.1.6 on 2021-03-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_product_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[(1, 'white'), (2, 'black'), (3, 'gray'), (4, 'blue'), (5, 'orange')], default=1, max_length=2, verbose_name='Цвет продукта'),
            preserve_default=False,
        ),
    ]
