# Generated by Django 3.1.6 on 2021-03-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210305_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='Изображение продукта'),
            preserve_default=False,
        ),
    ]
