# Generated by Django 3.1.3 on 2020-11-26 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
